language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install -r requirements.txt
script:
  - pep8 statestyle/__init__.py
  - pyflakes statestyle
  - coverage run test.py
after_success:
  - coveralls
