CROSSWALK = {1: {'ap': 'Ala.',
     'fips': '1',
     'name': 'Alabama',
     'postal': 'AL',
     'stateface': 'B',
     'type': 'state'},
 2: {'ap': 'Alaska',
     'fips': '2',
     'name': 'Alaska',
     'postal': 'AK',
     'stateface': 'A',
     'type': 'state'},
 4: {'ap': 'Ariz.',
     'fips': '4',
     'name': 'Arizona',
     'postal': 'AZ',
     'stateface': 'D',
     'type': 'state'},
 5: {'ap': 'Ark.',
     'fips': '5',
     'name': 'Arkansas',
     'postal': 'AR',
     'stateface': 'C',
     'type': 'state'},
 6: {'ap': 'Calif.',
     'fips': '6',
     'name': 'California',
     'postal': 'CA',
     'stateface': 'E',
     'type': 'state'},
 8: {'ap': 'Colo.',
     'fips': '8',
     'name': 'Colorado',
     'postal': 'CO',
     'stateface': 'F',
     'type': 'state'},
 9: {'ap': 'Conn.',
     'fips': '9',
     'name': 'Connecticut',
     'postal': 'CT',
     'stateface': 'G',
     'type': 'state'},
 10: {'ap': 'Del.',
      'fips': '10',
      'name': 'Delaware',
      'postal': 'DE',
      'stateface': 'H',
      'type': 'state'},
 11: {'ap': 'D.C.',
      'fips': '11',
      'name': 'District of Columbia',
      'postal': 'DC',
      'stateface': 'y',
      'type': ''},
 12: {'ap': 'Fla.',
      'fips': '12',
      'name': 'Florida',
      'postal': 'FL',
      'stateface': 'I',
      'type': 'state'},
 13: {'ap': 'Ga.',
      'fips': '13',
      'name': 'Georgia',
      'postal': 'GA',
      'stateface': 'J',
      'type': 'state'},
 15: {'ap': 'Hawaii',
      'fips': '15',
      'name': 'Hawaii',
      'postal': 'HI',
      'stateface': 'K',
      'type': 'state'},
 16: {'ap': 'Idaho',
      'fips': '16',
      'name': 'Idaho',
      'postal': 'ID',
      'stateface': 'M',
      'type': 'state'},
 17: {'ap': 'Ill.',
      'fips': '17',
      'name': 'Illinois',
      'postal': 'IL',
      'stateface': 'N',
      'type': 'state'},
 18: {'ap': 'Ind.',
      'fips': '18',
      'name': 'Indiana',
      'postal': 'IN',
      'stateface': 'O',
      'type': 'state'},
 19: {'ap': 'Iowa',
      'fips': '19',
      'name': 'Iowa',
      'postal': 'IA',
      'stateface': 'L',
      'type': 'state'},
 20: {'ap': 'Kan.',
      'fips': '20',
      'name': 'Kansas',
      'postal': 'KS',
      'stateface': 'P',
      'type': 'state'},
 21: {'ap': 'Ky.',
      'fips': '21',
      'name': 'Kentucky',
      'postal': 'KY',
      'stateface': 'Q',
      'type': 'state'},
 22: {'ap': 'La.',
      'fips': '22',
      'name': 'Louisiana',
      'postal': 'LA',
      'stateface': 'R',
      'type': 'state'},
 23: {'ap': 'Maine',
      'fips': '23',
      'name': 'Maine',
      'postal': 'ME',
      'stateface': 'U',
      'type': 'state'},
 24: {'ap': 'Md.',
      'fips': '24',
      'name': 'Maryland',
      'postal': 'MD',
      'stateface': 'T',
      'type': 'state'},
 25: {'ap': 'Mass.',
      'fips': '25',
      'name': 'Massachusetts',
      'postal': 'MA',
      'stateface': 'S',
      'type': 'state'},
 26: {'ap': 'Mich.',
      'fips': '26',
      'name': 'Michigan',
      'postal': 'MI',
      'stateface': 'V',
      'type': 'state'},
 27: {'ap': 'Minn.',
      'fips': '27',
      'name': 'Minnesota',
      'postal': 'MN',
      'stateface': 'W',
      'type': 'state'},
 28: {'ap': 'Miss.',
      'fips': '28',
      'name': 'Mississippi',
      'postal': 'MS',
      'stateface': 'Y',
      'type': 'state'},
 29: {'ap': 'Mo.',
      'fips': '29',
      'name': 'Missouri',
      'postal': 'MO',
      'stateface': 'X',
      'type': 'state'},
 30: {'ap': 'Mont.',
      'fips': '30',
      'name': 'Montana',
      'postal': 'MT',
      'stateface': 'Z',
      'type': 'state'},
 31: {'ap': 'Neb.',
      'fips': '31',
      'name': 'Nebraska',
      'postal': 'NE',
      'stateface': 'c',
      'type': 'state'},
 32: {'ap': 'Nev.',
      'fips': '32',
      'name': 'Nevada',
      'postal': 'NV',
      'stateface': 'g',
      'type': 'state'},
 33: {'ap': 'N.H.',
      'fips': '33',
      'name': 'New Hampshire',
      'postal': 'NH',
      'stateface': 'd',
      'type': 'state'},
 34: {'ap': 'N.J.',
      'fips': '34',
      'name': 'New Jersey',
      'postal': 'NJ',
      'stateface': 'e',
      'type': 'state'},
 35: {'ap': 'N.M.',
      'fips': '35',
      'name': 'New Mexico',
      'postal': 'NM',
      'stateface': 'f',
      'type': 'state'},
 36: {'ap': 'N.Y.',
      'fips': '36',
      'name': 'New York',
      'postal': 'NY',
      'stateface': 'h',
      'type': 'state'},
 37: {'ap': 'N.C.',
      'fips': '37',
      'name': 'North Carolina',
      'postal': 'NC',
      'stateface': 'a',
      'type': 'state'},
 38: {'ap': 'N.D.',
      'fips': '38',
      'name': 'North Dakota',
      'postal': 'ND',
      'stateface': 'b',
      'type': 'state'},
 39: {'ap': 'Ohio',
      'fips': '39',
      'name': 'Ohio',
      'postal': 'OH',
      'stateface': 'i',
      'type': 'state'},
 40: {'ap': 'Okla.',
      'fips': '40',
      'name': 'Oklahoma',
      'postal': 'OK',
      'stateface': 'j',
      'type': 'state'},
 41: {'ap': 'Ore.',
      'fips': '41',
      'name': 'Oregon',
      'postal': 'OR',
      'stateface': 'k',
      'type': 'state'},
 42: {'ap': 'Pa.',
      'fips': '42',
      'name': 'Pennsylvania',
      'postal': 'PA',
      'stateface': 'l',
      'type': 'state'},
 44: {'ap': 'R.I.',
      'fips': '44',
      'name': 'Rhode Island',
      'postal': 'RI',
      'stateface': 'm',
      'type': 'state'},
 45: {'ap': 'S.C.',
      'fips': '45',
      'name': 'South Carolina',
      'postal': 'SC',
      'stateface': 'n',
      'type': 'state'},
 46: {'ap': 'S.D.',
      'fips': '46',
      'name': 'South Dakota',
      'postal': 'SD',
      'stateface': 'o',
      'type': 'state'},
 47: {'ap': 'Tenn.',
      'fips': '47',
      'name': 'Tennessee',
      'postal': 'TN',
      'stateface': 'p',
      'type': 'state'},
 48: {'ap': 'Texas',
      'fips': '48',
      'name': 'Texas',
      'postal': 'TX',
      'stateface': 'q',
      'type': 'state'},
 49: {'ap': 'Utah',
      'fips': '49',
      'name': 'Utah',
      'postal': 'UT',
      'stateface': 'r',
      'type': 'state'},
 50: {'ap': 'Vt.',
      'fips': '50',
      'name': 'Vermont',
      'postal': 'VT',
      'stateface': 't',
      'type': 'state'},
 51: {'ap': 'Va.',
      'fips': '51',
      'name': 'Virginia',
      'postal': 'VA',
      'stateface': 's',
      'type': 'state'},
 53: {'ap': 'Wash.',
      'fips': '53',
      'name': 'Washington',
      'postal': 'WA',
      'stateface': 'u',
      'type': 'state'},
 54: {'ap': 'W.Va.',
      'fips': '54',
      'name': 'West Virginia',
      'postal': 'WV',
      'stateface': 'w',
      'type': 'state'},
 55: {'ap': 'Wis.',
      'fips': '55',
      'name': 'Wisconsin',
      'postal': 'WI',
      'stateface': 'v',
      'type': 'state'},
 56: {'ap': 'Wyo.',
      'fips': '56',
      'name': 'Wyoming',
      'postal': 'WY',
      'stateface': 'x',
      'type': 'state'},
 60: {'ap': '',
      'fips': '60',
      'name': 'American Samoa',
      'postal': 'AS',
      'stateface': '',
      'type': ''},
 64: {'ap': '',
      'fips': '64',
      'name': 'Federated States of Micronesia',
      'postal': 'FM',
      'stateface': '',
      'type': ''},
 66: {'ap': '',
      'fips': '66',
      'name': 'Guam',
      'postal': 'GU',
      'stateface': '',
      'type': ''},
 68: {'ap': '',
      'fips': '68',
      'name': 'Marshall Islands',
      'postal': 'MH',
      'stateface': '',
      'type': ''},
 69: {'ap': '',
      'fips': '69',
      'name': 'Northern Mariana Islands',
      'postal': 'MP',
      'stateface': '',
      'type': ''},
 70: {'ap': '',
      'fips': '70',
      'name': 'Palau',
      'postal': 'PW',
      'stateface': '',
      'type': ''},
 72: {'ap': '',
      'fips': '72',
      'name': 'Puerto Rico',
      'postal': 'PR',
      'stateface': '',
      'type': ''},
 78: {'ap': '',
      'fips': '78',
      'name': 'Virgin Islands',
      'postal': 'VI',
      'stateface': '',
      'type': ''},
 '1': {'ap': 'Ala.',
       'fips': '1',
       'name': 'Alabama',
       'postal': 'AL',
       'stateface': 'B',
       'type': 'state'},
 '10': {'ap': 'Del.',
        'fips': '10',
        'name': 'Delaware',
        'postal': 'DE',
        'stateface': 'H',
        'type': 'state'},
 '11': {'ap': 'D.C.',
        'fips': '11',
        'name': 'District of Columbia',
        'postal': 'DC',
        'stateface': 'y',
        'type': ''},
 '12': {'ap': 'Fla.',
        'fips': '12',
        'name': 'Florida',
        'postal': 'FL',
        'stateface': 'I',
        'type': 'state'},
 '13': {'ap': 'Ga.',
        'fips': '13',
        'name': 'Georgia',
        'postal': 'GA',
        'stateface': 'J',
        'type': 'state'},
 '15': {'ap': 'Hawaii',
        'fips': '15',
        'name': 'Hawaii',
        'postal': 'HI',
        'stateface': 'K',
        'type': 'state'},
 '16': {'ap': 'Idaho',
        'fips': '16',
        'name': 'Idaho',
        'postal': 'ID',
        'stateface': 'M',
        'type': 'state'},
 '17': {'ap': 'Ill.',
        'fips': '17',
        'name': 'Illinois',
        'postal': 'IL',
        'stateface': 'N',
        'type': 'state'},
 '18': {'ap': 'Ind.',
        'fips': '18',
        'name': 'Indiana',
        'postal': 'IN',
        'stateface': 'O',
        'type': 'state'},
 '19': {'ap': 'Iowa',
        'fips': '19',
        'name': 'Iowa',
        'postal': 'IA',
        'stateface': 'L',
        'type': 'state'},
 '2': {'ap': 'Alaska',
       'fips': '2',
       'name': 'Alaska',
       'postal': 'AK',
       'stateface': 'A',
       'type': 'state'},
 '20': {'ap': 'Kan.',
        'fips': '20',
        'name': 'Kansas',
        'postal': 'KS',
        'stateface': 'P',
        'type': 'state'},
 '21': {'ap': 'Ky.',
        'fips': '21',
        'name': 'Kentucky',
        'postal': 'KY',
        'stateface': 'Q',
        'type': 'state'},
 '22': {'ap': 'La.',
        'fips': '22',
        'name': 'Louisiana',
        'postal': 'LA',
        'stateface': 'R',
        'type': 'state'},
 '23': {'ap': 'Maine',
        'fips': '23',
        'name': 'Maine',
        'postal': 'ME',
        'stateface': 'U',
        'type': 'state'},
 '24': {'ap': 'Md.',
        'fips': '24',
        'name': 'Maryland',
        'postal': 'MD',
        'stateface': 'T',
        'type': 'state'},
 '25': {'ap': 'Mass.',
        'fips': '25',
        'name': 'Massachusetts',
        'postal': 'MA',
        'stateface': 'S',
        'type': 'state'},
 '26': {'ap': 'Mich.',
        'fips': '26',
        'name': 'Michigan',
        'postal': 'MI',
        'stateface': 'V',
        'type': 'state'},
 '27': {'ap': 'Minn.',
        'fips': '27',
        'name': 'Minnesota',
        'postal': 'MN',
        'stateface': 'W',
        'type': 'state'},
 '28': {'ap': 'Miss.',
        'fips': '28',
        'name': 'Mississippi',
        'postal': 'MS',
        'stateface': 'Y',
        'type': 'state'},
 '29': {'ap': 'Mo.',
        'fips': '29',
        'name': 'Missouri',
        'postal': 'MO',
        'stateface': 'X',
        'type': 'state'},
 '30': {'ap': 'Mont.',
        'fips': '30',
        'name': 'Montana',
        'postal': 'MT',
        'stateface': 'Z',
        'type': 'state'},
 '31': {'ap': 'Neb.',
        'fips': '31',
        'name': 'Nebraska',
        'postal': 'NE',
        'stateface': 'c',
        'type': 'state'},
 '32': {'ap': 'Nev.',
        'fips': '32',
        'name': 'Nevada',
        'postal': 'NV',
        'stateface': 'g',
        'type': 'state'},
 '33': {'ap': 'N.H.',
        'fips': '33',
        'name': 'New Hampshire',
        'postal': 'NH',
        'stateface': 'd',
        'type': 'state'},
 '34': {'ap': 'N.J.',
        'fips': '34',
        'name': 'New Jersey',
        'postal': 'NJ',
        'stateface': 'e',
        'type': 'state'},
 '35': {'ap': 'N.M.',
        'fips': '35',
        'name': 'New Mexico',
        'postal': 'NM',
        'stateface': 'f',
        'type': 'state'},
 '36': {'ap': 'N.Y.',
        'fips': '36',
        'name': 'New York',
        'postal': 'NY',
        'stateface': 'h',
        'type': 'state'},
 '37': {'ap': 'N.C.',
        'fips': '37',
        'name': 'North Carolina',
        'postal': 'NC',
        'stateface': 'a',
        'type': 'state'},
 '38': {'ap': 'N.D.',
        'fips': '38',
        'name': 'North Dakota',
        'postal': 'ND',
        'stateface': 'b',
        'type': 'state'},
 '39': {'ap': 'Ohio',
        'fips': '39',
        'name': 'Ohio',
        'postal': 'OH',
        'stateface': 'i',
        'type': 'state'},
 '4': {'ap': 'Ariz.',
       'fips': '4',
       'name': 'Arizona',
       'postal': 'AZ',
       'stateface': 'D',
       'type': 'state'},
 '40': {'ap': 'Okla.',
        'fips': '40',
        'name': 'Oklahoma',
        'postal': 'OK',
        'stateface': 'j',
        'type': 'state'},
 '41': {'ap': 'Ore.',
        'fips': '41',
        'name': 'Oregon',
        'postal': 'OR',
        'stateface': 'k',
        'type': 'state'},
 '42': {'ap': 'Pa.',
        'fips': '42',
        'name': 'Pennsylvania',
        'postal': 'PA',
        'stateface': 'l',
        'type': 'state'},
 '44': {'ap': 'R.I.',
        'fips': '44',
        'name': 'Rhode Island',
        'postal': 'RI',
        'stateface': 'm',
        'type': 'state'},
 '45': {'ap': 'S.C.',
        'fips': '45',
        'name': 'South Carolina',
        'postal': 'SC',
        'stateface': 'n',
        'type': 'state'},
 '46': {'ap': 'S.D.',
        'fips': '46',
        'name': 'South Dakota',
        'postal': 'SD',
        'stateface': 'o',
        'type': 'state'},
 '47': {'ap': 'Tenn.',
        'fips': '47',
        'name': 'Tennessee',
        'postal': 'TN',
        'stateface': 'p',
        'type': 'state'},
 '48': {'ap': 'Texas',
        'fips': '48',
        'name': 'Texas',
        'postal': 'TX',
        'stateface': 'q',
        'type': 'state'},
 '49': {'ap': 'Utah',
        'fips': '49',
        'name': 'Utah',
        'postal': 'UT',
        'stateface': 'r',
        'type': 'state'},
 '5': {'ap': 'Ark.',
       'fips': '5',
       'name': 'Arkansas',
       'postal': 'AR',
       'stateface': 'C',
       'type': 'state'},
 '50': {'ap': 'Vt.',
        'fips': '50',
        'name': 'Vermont',
        'postal': 'VT',
        'stateface': 't',
        'type': 'state'},
 '51': {'ap': 'Va.',
        'fips': '51',
        'name': 'Virginia',
        'postal': 'VA',
        'stateface': 's',
        'type': 'state'},
 '53': {'ap': 'Wash.',
        'fips': '53',
        'name': 'Washington',
        'postal': 'WA',
        'stateface': 'u',
        'type': 'state'},
 '54': {'ap': 'W.Va.',
        'fips': '54',
        'name': 'West Virginia',
        'postal': 'WV',
        'stateface': 'w',
        'type': 'state'},
 '55': {'ap': 'Wis.',
        'fips': '55',
        'name': 'Wisconsin',
        'postal': 'WI',
        'stateface': 'v',
        'type': 'state'},
 '56': {'ap': 'Wyo.',
        'fips': '56',
        'name': 'Wyoming',
        'postal': 'WY',
        'stateface': 'x',
        'type': 'state'},
 '6': {'ap': 'Calif.',
       'fips': '6',
       'name': 'California',
       'postal': 'CA',
       'stateface': 'E',
       'type': 'state'},
 '60': {'ap': '',
        'fips': '60',
        'name': 'American Samoa',
        'postal': 'AS',
        'stateface': '',
        'type': ''},
 '64': {'ap': '',
        'fips': '64',
        'name': 'Federated States of Micronesia',
        'postal': 'FM',
        'stateface': '',
        'type': ''},
 '66': {'ap': '',
        'fips': '66',
        'name': 'Guam',
        'postal': 'GU',
        'stateface': '',
        'type': ''},
 '68': {'ap': '',
        'fips': '68',
        'name': 'Marshall Islands',
        'postal': 'MH',
        'stateface': '',
        'type': ''},
 '69': {'ap': '',
        'fips': '69',
        'name': 'Northern Mariana Islands',
        'postal': 'MP',
        'stateface': '',
        'type': ''},
 '70': {'ap': '',
        'fips': '70',
        'name': 'Palau',
        'postal': 'PW',
        'stateface': '',
        'type': ''},
 '72': {'ap': '',
        'fips': '72',
        'name': 'Puerto Rico',
        'postal': 'PR',
        'stateface': '',
        'type': ''},
 '78': {'ap': '',
        'fips': '78',
        'name': 'Virgin Islands',
        'postal': 'VI',
        'stateface': '',
        'type': ''},
 '8': {'ap': 'Colo.',
       'fips': '8',
       'name': 'Colorado',
       'postal': 'CO',
       'stateface': 'F',
       'type': 'state'},
 '9': {'ap': 'Conn.',
       'fips': '9',
       'name': 'Connecticut',
       'postal': 'CT',
       'stateface': 'G',
       'type': 'state'},
 'AK': {'ap': 'Alaska',
        'fips': '2',
        'name': 'Alaska',
        'postal': 'AK',
        'stateface': 'A',
        'type': 'state'},
 'AL': {'ap': 'Ala.',
        'fips': '1',
        'name': 'Alabama',
        'postal': 'AL',
        'stateface': 'B',
        'type': 'state'},
 'AR': {'ap': 'Ark.',
        'fips': '5',
        'name': 'Arkansas',
        'postal': 'AR',
        'stateface': 'C',
        'type': 'state'},
 'AS': {'ap': '',
        'fips': '60',
        'name': 'American Samoa',
        'postal': 'AS',
        'stateface': '',
        'type': ''},
 'AZ': {'ap': 'Ariz.',
        'fips': '4',
        'name': 'Arizona',
        'postal': 'AZ',
        'stateface': 'D',
        'type': 'state'},
 'Ala.': {'ap': 'Ala.',
          'fips': '1',
          'name': 'Alabama',
          'postal': 'AL',
          'stateface': 'B',
          'type': 'state'},
 'Alabama': {'ap': 'Ala.',
             'fips': '1',
             'name': 'Alabama',
             'postal': 'AL',
             'stateface': 'B',
             'type': 'state'},
 'Alaska': {'ap': 'Alaska',
            'fips': '2',
            'name': 'Alaska',
            'postal': 'AK',
            'stateface': 'A',
            'type': 'state'},
 'American Samoa': {'ap': '',
                    'fips': '60',
                    'name': 'American Samoa',
                    'postal': 'AS',
                    'stateface': '',
                    'type': ''},
 'Ariz.': {'ap': 'Ariz.',
           'fips': '4',
           'name': 'Arizona',
           'postal': 'AZ',
           'stateface': 'D',
           'type': 'state'},
 'Arizona': {'ap': 'Ariz.',
             'fips': '4',
             'name': 'Arizona',
             'postal': 'AZ',
             'stateface': 'D',
             'type': 'state'},
 'Ark.': {'ap': 'Ark.',
          'fips': '5',
          'name': 'Arkansas',
          'postal': 'AR',
          'stateface': 'C',
          'type': 'state'},
 'Arkansas': {'ap': 'Ark.',
              'fips': '5',
              'name': 'Arkansas',
              'postal': 'AR',
              'stateface': 'C',
              'type': 'state'},
 'CA': {'ap': 'Calif.',
        'fips': '6',
        'name': 'California',
        'postal': 'CA',
        'stateface': 'E',
        'type': 'state'},
 'CO': {'ap': 'Colo.',
        'fips': '8',
        'name': 'Colorado',
        'postal': 'CO',
        'stateface': 'F',
        'type': 'state'},
 'CT': {'ap': 'Conn.',
        'fips': '9',
        'name': 'Connecticut',
        'postal': 'CT',
        'stateface': 'G',
        'type': 'state'},
 'Calif.': {'ap': 'Calif.',
            'fips': '6',
            'name': 'California',
            'postal': 'CA',
            'stateface': 'E',
            'type': 'state'},
 'California': {'ap': 'Calif.',
                'fips': '6',
                'name': 'California',
                'postal': 'CA',
                'stateface': 'E',
                'type': 'state'},
 'Colo.': {'ap': 'Colo.',
           'fips': '8',
           'name': 'Colorado',
           'postal': 'CO',
           'stateface': 'F',
           'type': 'state'},
 'Colorado': {'ap': 'Colo.',
              'fips': '8',
              'name': 'Colorado',
              'postal': 'CO',
              'stateface': 'F',
              'type': 'state'},
 'Conn.': {'ap': 'Conn.',
           'fips': '9',
           'name': 'Connecticut',
           'postal': 'CT',
           'stateface': 'G',
           'type': 'state'},
 'Connecticut': {'ap': 'Conn.',
                 'fips': '9',
                 'name': 'Connecticut',
                 'postal': 'CT',
                 'stateface': 'G',
                 'type': 'state'},
 'D.C.': {'ap': 'D.C.',
          'fips': '11',
          'name': 'District of Columbia',
          'postal': 'DC',
          'stateface': 'y',
          'type': ''},
 'DC': {'ap': 'D.C.',
        'fips': '11',
        'name': 'District of Columbia',
        'postal': 'DC',
        'stateface': 'y',
        'type': ''},
 'DE': {'ap': 'Del.',
        'fips': '10',
        'name': 'Delaware',
        'postal': 'DE',
        'stateface': 'H',
        'type': 'state'},
 'Del.': {'ap': 'Del.',
          'fips': '10',
          'name': 'Delaware',
          'postal': 'DE',
          'stateface': 'H',
          'type': 'state'},
 'Delaware': {'ap': 'Del.',
              'fips': '10',
              'name': 'Delaware',
              'postal': 'DE',
              'stateface': 'H',
              'type': 'state'},
 'District of Columbia': {'ap': 'D.C.',
                          'fips': '11',
                          'name': 'District of Columbia',
                          'postal': 'DC',
                          'stateface': 'y',
                          'type': ''},
 'FL': {'ap': 'Fla.',
        'fips': '12',
        'name': 'Florida',
        'postal': 'FL',
        'stateface': 'I',
        'type': 'state'},
 'FM': {'ap': '',
        'fips': '64',
        'name': 'Federated States of Micronesia',
        'postal': 'FM',
        'stateface': '',
        'type': ''},
 'Federated States of Micronesia': {'ap': '',
                                    'fips': '64',
                                    'name': 'Federated States of Micronesia',
                                    'postal': 'FM',
                                    'stateface': '',
                                    'type': ''},
 'Fla.': {'ap': 'Fla.',
          'fips': '12',
          'name': 'Florida',
          'postal': 'FL',
          'stateface': 'I',
          'type': 'state'},
 'Florida': {'ap': 'Fla.',
             'fips': '12',
             'name': 'Florida',
             'postal': 'FL',
             'stateface': 'I',
             'type': 'state'},
 'GA': {'ap': 'Ga.',
        'fips': '13',
        'name': 'Georgia',
        'postal': 'GA',
        'stateface': 'J',
        'type': 'state'},
 'GU': {'ap': '',
        'fips': '66',
        'name': 'Guam',
        'postal': 'GU',
        'stateface': '',
        'type': ''},
 'Ga.': {'ap': 'Ga.',
         'fips': '13',
         'name': 'Georgia',
         'postal': 'GA',
         'stateface': 'J',
         'type': 'state'},
 'Georgia': {'ap': 'Ga.',
             'fips': '13',
             'name': 'Georgia',
             'postal': 'GA',
             'stateface': 'J',
             'type': 'state'},
 'Guam': {'ap': '',
          'fips': '66',
          'name': 'Guam',
          'postal': 'GU',
          'stateface': '',
          'type': ''},
 'HI': {'ap': 'Hawaii',
        'fips': '15',
        'name': 'Hawaii',
        'postal': 'HI',
        'stateface': 'K',
        'type': 'state'},
 'Hawaii': {'ap': 'Hawaii',
            'fips': '15',
            'name': 'Hawaii',
            'postal': 'HI',
            'stateface': 'K',
            'type': 'state'},
 'IA': {'ap': 'Iowa',
        'fips': '19',
        'name': 'Iowa',
        'postal': 'IA',
        'stateface': 'L',
        'type': 'state'},
 'ID': {'ap': 'Idaho',
        'fips': '16',
        'name': 'Idaho',
        'postal': 'ID',
        'stateface': 'M',
        'type': 'state'},
 'IL': {'ap': 'Ill.',
        'fips': '17',
        'name': 'Illinois',
        'postal': 'IL',
        'stateface': 'N',
        'type': 'state'},
 'IN': {'ap': 'Ind.',
        'fips': '18',
        'name': 'Indiana',
        'postal': 'IN',
        'stateface': 'O',
        'type': 'state'},
 'Idaho': {'ap': 'Idaho',
           'fips': '16',
           'name': 'Idaho',
           'postal': 'ID',
           'stateface': 'M',
           'type': 'state'},
 'Ill.': {'ap': 'Ill.',
          'fips': '17',
          'name': 'Illinois',
          'postal': 'IL',
          'stateface': 'N',
          'type': 'state'},
 'Illinois': {'ap': 'Ill.',
              'fips': '17',
              'name': 'Illinois',
              'postal': 'IL',
              'stateface': 'N',
              'type': 'state'},
 'Ind.': {'ap': 'Ind.',
          'fips': '18',
          'name': 'Indiana',
          'postal': 'IN',
          'stateface': 'O',
          'type': 'state'},
 'Indiana': {'ap': 'Ind.',
             'fips': '18',
             'name': 'Indiana',
             'postal': 'IN',
             'stateface': 'O',
             'type': 'state'},
 'Iowa': {'ap': 'Iowa',
          'fips': '19',
          'name': 'Iowa',
          'postal': 'IA',
          'stateface': 'L',
          'type': 'state'},
 'KS': {'ap': 'Kan.',
        'fips': '20',
        'name': 'Kansas',
        'postal': 'KS',
        'stateface': 'P',
        'type': 'state'},
 'KY': {'ap': 'Ky.',
        'fips': '21',
        'name': 'Kentucky',
        'postal': 'KY',
        'stateface': 'Q',
        'type': 'state'},
 'Kan.': {'ap': 'Kan.',
          'fips': '20',
          'name': 'Kansas',
          'postal': 'KS',
          'stateface': 'P',
          'type': 'state'},
 'Kansas': {'ap': 'Kan.',
            'fips': '20',
            'name': 'Kansas',
            'postal': 'KS',
            'stateface': 'P',
            'type': 'state'},
 'Kentucky': {'ap': 'Ky.',
              'fips': '21',
              'name': 'Kentucky',
              'postal': 'KY',
              'stateface': 'Q',
              'type': 'state'},
 'Ky.': {'ap': 'Ky.',
         'fips': '21',
         'name': 'Kentucky',
         'postal': 'KY',
         'stateface': 'Q',
         'type': 'state'},
 'LA': {'ap': 'La.',
        'fips': '22',
        'name': 'Louisiana',
        'postal': 'LA',
        'stateface': 'R',
        'type': 'state'},
 'La.': {'ap': 'La.',
         'fips': '22',
         'name': 'Louisiana',
         'postal': 'LA',
         'stateface': 'R',
         'type': 'state'},
 'Louisiana': {'ap': 'La.',
               'fips': '22',
               'name': 'Louisiana',
               'postal': 'LA',
               'stateface': 'R',
               'type': 'state'},
 'MA': {'ap': 'Mass.',
        'fips': '25',
        'name': 'Massachusetts',
        'postal': 'MA',
        'stateface': 'S',
        'type': 'state'},
 'MD': {'ap': 'Md.',
        'fips': '24',
        'name': 'Maryland',
        'postal': 'MD',
        'stateface': 'T',
        'type': 'state'},
 'ME': {'ap': 'Maine',
        'fips': '23',
        'name': 'Maine',
        'postal': 'ME',
        'stateface': 'U',
        'type': 'state'},
 'MH': {'ap': '',
        'fips': '68',
        'name': 'Marshall Islands',
        'postal': 'MH',
        'stateface': '',
        'type': ''},
 'MI': {'ap': 'Mich.',
        'fips': '26',
        'name': 'Michigan',
        'postal': 'MI',
        'stateface': 'V',
        'type': 'state'},
 'MN': {'ap': 'Minn.',
        'fips': '27',
        'name': 'Minnesota',
        'postal': 'MN',
        'stateface': 'W',
        'type': 'state'},
 'MO': {'ap': 'Mo.',
        'fips': '29',
        'name': 'Missouri',
        'postal': 'MO',
        'stateface': 'X',
        'type': 'state'},
 'MP': {'ap': '',
        'fips': '69',
        'name': 'Northern Mariana Islands',
        'postal': 'MP',
        'stateface': '',
        'type': ''},
 'MS': {'ap': 'Miss.',
        'fips': '28',
        'name': 'Mississippi',
        'postal': 'MS',
        'stateface': 'Y',
        'type': 'state'},
 'MT': {'ap': 'Mont.',
        'fips': '30',
        'name': 'Montana',
        'postal': 'MT',
        'stateface': 'Z',
        'type': 'state'},
 'Maine': {'ap': 'Maine',
           'fips': '23',
           'name': 'Maine',
           'postal': 'ME',
           'stateface': 'U',
           'type': 'state'},
 'Marshall Islands': {'ap': '',
                      'fips': '68',
                      'name': 'Marshall Islands',
                      'postal': 'MH',
                      'stateface': '',
                      'type': ''},
 'Maryland': {'ap': 'Md.',
              'fips': '24',
              'name': 'Maryland',
              'postal': 'MD',
              'stateface': 'T',
              'type': 'state'},
 'Mass.': {'ap': 'Mass.',
           'fips': '25',
           'name': 'Massachusetts',
           'postal': 'MA',
           'stateface': 'S',
           'type': 'state'},
 'Massachusetts': {'ap': 'Mass.',
                   'fips': '25',
                   'name': 'Massachusetts',
                   'postal': 'MA',
                   'stateface': 'S',
                   'type': 'state'},
 'Md.': {'ap': 'Md.',
         'fips': '24',
         'name': 'Maryland',
         'postal': 'MD',
         'stateface': 'T',
         'type': 'state'},
 'Mich.': {'ap': 'Mich.',
           'fips': '26',
           'name': 'Michigan',
           'postal': 'MI',
           'stateface': 'V',
           'type': 'state'},
 'Michigan': {'ap': 'Mich.',
              'fips': '26',
              'name': 'Michigan',
              'postal': 'MI',
              'stateface': 'V',
              'type': 'state'},
 'Minn.': {'ap': 'Minn.',
           'fips': '27',
           'name': 'Minnesota',
           'postal': 'MN',
           'stateface': 'W',
           'type': 'state'},
 'Minnesota': {'ap': 'Minn.',
               'fips': '27',
               'name': 'Minnesota',
               'postal': 'MN',
               'stateface': 'W',
               'type': 'state'},
 'Miss.': {'ap': 'Miss.',
           'fips': '28',
           'name': 'Mississippi',
           'postal': 'MS',
           'stateface': 'Y',
           'type': 'state'},
 'Mississippi': {'ap': 'Miss.',
                 'fips': '28',
                 'name': 'Mississippi',
                 'postal': 'MS',
                 'stateface': 'Y',
                 'type': 'state'},
 'Missouri': {'ap': 'Mo.',
              'fips': '29',
              'name': 'Missouri',
              'postal': 'MO',
              'stateface': 'X',
              'type': 'state'},
 'Mo.': {'ap': 'Mo.',
         'fips': '29',
         'name': 'Missouri',
         'postal': 'MO',
         'stateface': 'X',
         'type': 'state'},
 'Mont.': {'ap': 'Mont.',
           'fips': '30',
           'name': 'Montana',
           'postal': 'MT',
           'stateface': 'Z',
           'type': 'state'},
 'Montana': {'ap': 'Mont.',
             'fips': '30',
             'name': 'Montana',
             'postal': 'MT',
             'stateface': 'Z',
             'type': 'state'},
 'N.C.': {'ap': 'N.C.',
          'fips': '37',
          'name': 'North Carolina',
          'postal': 'NC',
          'stateface': 'a',
          'type': 'state'},
 'N.D.': {'ap': 'N.D.',
          'fips': '38',
          'name': 'North Dakota',
          'postal': 'ND',
          'stateface': 'b',
          'type': 'state'},
 'N.H.': {'ap': 'N.H.',
          'fips': '33',
          'name': 'New Hampshire',
          'postal': 'NH',
          'stateface': 'd',
          'type': 'state'},
 'N.J.': {'ap': 'N.J.',
          'fips': '34',
          'name': 'New Jersey',
          'postal': 'NJ',
          'stateface': 'e',
          'type': 'state'},
 'N.M.': {'ap': 'N.M.',
          'fips': '35',
          'name': 'New Mexico',
          'postal': 'NM',
          'stateface': 'f',
          'type': 'state'},
 'N.Y.': {'ap': 'N.Y.',
          'fips': '36',
          'name': 'New York',
          'postal': 'NY',
          'stateface': 'h',
          'type': 'state'},
 'NC': {'ap': 'N.C.',
        'fips': '37',
        'name': 'North Carolina',
        'postal': 'NC',
        'stateface': 'a',
        'type': 'state'},
 'ND': {'ap': 'N.D.',
        'fips': '38',
        'name': 'North Dakota',
        'postal': 'ND',
        'stateface': 'b',
        'type': 'state'},
 'NE': {'ap': 'Neb.',
        'fips': '31',
        'name': 'Nebraska',
        'postal': 'NE',
        'stateface': 'c',
        'type': 'state'},
 'NH': {'ap': 'N.H.',
        'fips': '33',
        'name': 'New Hampshire',
        'postal': 'NH',
        'stateface': 'd',
        'type': 'state'},
 'NJ': {'ap': 'N.J.',
        'fips': '34',
        'name': 'New Jersey',
        'postal': 'NJ',
        'stateface': 'e',
        'type': 'state'},
 'NM': {'ap': 'N.M.',
        'fips': '35',
        'name': 'New Mexico',
        'postal': 'NM',
        'stateface': 'f',
        'type': 'state'},
 'NV': {'ap': 'Nev.',
        'fips': '32',
        'name': 'Nevada',
        'postal': 'NV',
        'stateface': 'g',
        'type': 'state'},
 'NY': {'ap': 'N.Y.',
        'fips': '36',
        'name': 'New York',
        'postal': 'NY',
        'stateface': 'h',
        'type': 'state'},
 'Neb.': {'ap': 'Neb.',
          'fips': '31',
          'name': 'Nebraska',
          'postal': 'NE',
          'stateface': 'c',
          'type': 'state'},
 'Nebraska': {'ap': 'Neb.',
              'fips': '31',
              'name': 'Nebraska',
              'postal': 'NE',
              'stateface': 'c',
              'type': 'state'},
 'Nev.': {'ap': 'Nev.',
          'fips': '32',
          'name': 'Nevada',
          'postal': 'NV',
          'stateface': 'g',
          'type': 'state'},
 'Nevada': {'ap': 'Nev.',
            'fips': '32',
            'name': 'Nevada',
            'postal': 'NV',
            'stateface': 'g',
            'type': 'state'},
 'New Hampshire': {'ap': 'N.H.',
                   'fips': '33',
                   'name': 'New Hampshire',
                   'postal': 'NH',
                   'stateface': 'd',
                   'type': 'state'},
 'New Jersey': {'ap': 'N.J.',
                'fips': '34',
                'name': 'New Jersey',
                'postal': 'NJ',
                'stateface': 'e',
                'type': 'state'},
 'New Mexico': {'ap': 'N.M.',
                'fips': '35',
                'name': 'New Mexico',
                'postal': 'NM',
                'stateface': 'f',
                'type': 'state'},
 'New York': {'ap': 'N.Y.',
              'fips': '36',
              'name': 'New York',
              'postal': 'NY',
              'stateface': 'h',
              'type': 'state'},
 'North Carolina': {'ap': 'N.C.',
                    'fips': '37',
                    'name': 'North Carolina',
                    'postal': 'NC',
                    'stateface': 'a',
                    'type': 'state'},
 'North Dakota': {'ap': 'N.D.',
                  'fips': '38',
                  'name': 'North Dakota',
                  'postal': 'ND',
                  'stateface': 'b',
                  'type': 'state'},
 'Northern Mariana Islands': {'ap': '',
                              'fips': '69',
                              'name': 'Northern Mariana Islands',
                              'postal': 'MP',
                              'stateface': '',
                              'type': ''},
 'OH': {'ap': 'Ohio',
        'fips': '39',
        'name': 'Ohio',
        'postal': 'OH',
        'stateface': 'i',
        'type': 'state'},
 'OK': {'ap': 'Okla.',
        'fips': '40',
        'name': 'Oklahoma',
        'postal': 'OK',
        'stateface': 'j',
        'type': 'state'},
 'OR': {'ap': 'Ore.',
        'fips': '41',
        'name': 'Oregon',
        'postal': 'OR',
        'stateface': 'k',
        'type': 'state'},
 'Ohio': {'ap': 'Ohio',
          'fips': '39',
          'name': 'Ohio',
          'postal': 'OH',
          'stateface': 'i',
          'type': 'state'},
 'Okla.': {'ap': 'Okla.',
           'fips': '40',
           'name': 'Oklahoma',
           'postal': 'OK',
           'stateface': 'j',
           'type': 'state'},
 'Oklahoma': {'ap': 'Okla.',
              'fips': '40',
              'name': 'Oklahoma',
              'postal': 'OK',
              'stateface': 'j',
              'type': 'state'},
 'Ore.': {'ap': 'Ore.',
          'fips': '41',
          'name': 'Oregon',
          'postal': 'OR',
          'stateface': 'k',
          'type': 'state'},
 'Oregon': {'ap': 'Ore.',
            'fips': '41',
            'name': 'Oregon',
            'postal': 'OR',
            'stateface': 'k',
            'type': 'state'},
 'PA': {'ap': 'Pa.',
        'fips': '42',
        'name': 'Pennsylvania',
        'postal': 'PA',
        'stateface': 'l',
        'type': 'state'},
 'PR': {'ap': '',
        'fips': '72',
        'name': 'Puerto Rico',
        'postal': 'PR',
        'stateface': '',
        'type': ''},
 'PW': {'ap': '',
        'fips': '70',
        'name': 'Palau',
        'postal': 'PW',
        'stateface': '',
        'type': ''},
 'Pa.': {'ap': 'Pa.',
         'fips': '42',
         'name': 'Pennsylvania',
         'postal': 'PA',
         'stateface': 'l',
         'type': 'state'},
 'Palau': {'ap': '',
           'fips': '70',
           'name': 'Palau',
           'postal': 'PW',
           'stateface': '',
           'type': ''},
 'Pennsylvania': {'ap': 'Pa.',
                  'fips': '42',
                  'name': 'Pennsylvania',
                  'postal': 'PA',
                  'stateface': 'l',
                  'type': 'state'},
 'Puerto Rico': {'ap': '',
                 'fips': '72',
                 'name': 'Puerto Rico',
                 'postal': 'PR',
                 'stateface': '',
                 'type': ''},
 'R.I.': {'ap': 'R.I.',
          'fips': '44',
          'name': 'Rhode Island',
          'postal': 'RI',
          'stateface': 'm',
          'type': 'state'},
 'RI': {'ap': 'R.I.',
        'fips': '44',
        'name': 'Rhode Island',
        'postal': 'RI',
        'stateface': 'm',
        'type': 'state'},
 'Rhode Island': {'ap': 'R.I.',
                  'fips': '44',
                  'name': 'Rhode Island',
                  'postal': 'RI',
                  'stateface': 'm',
                  'type': 'state'},
 'S.C.': {'ap': 'S.C.',
          'fips': '45',
          'name': 'South Carolina',
          'postal': 'SC',
          'stateface': 'n',
          'type': 'state'},
 'S.D.': {'ap': 'S.D.',
          'fips': '46',
          'name': 'South Dakota',
          'postal': 'SD',
          'stateface': 'o',
          'type': 'state'},
 'SC': {'ap': 'S.C.',
        'fips': '45',
        'name': 'South Carolina',
        'postal': 'SC',
        'stateface': 'n',
        'type': 'state'},
 'SD': {'ap': 'S.D.',
        'fips': '46',
        'name': 'South Dakota',
        'postal': 'SD',
        'stateface': 'o',
        'type': 'state'},
 'South Carolina': {'ap': 'S.C.',
                    'fips': '45',
                    'name': 'South Carolina',
                    'postal': 'SC',
                    'stateface': 'n',
                    'type': 'state'},
 'South Dakota': {'ap': 'S.D.',
                  'fips': '46',
                  'name': 'South Dakota',
                  'postal': 'SD',
                  'stateface': 'o',
                  'type': 'state'},
 'TN': {'ap': 'Tenn.',
        'fips': '47',
        'name': 'Tennessee',
        'postal': 'TN',
        'stateface': 'p',
        'type': 'state'},
 'TX': {'ap': 'Texas',
        'fips': '48',
        'name': 'Texas',
        'postal': 'TX',
        'stateface': 'q',
        'type': 'state'},
 'Tenn.': {'ap': 'Tenn.',
           'fips': '47',
           'name': 'Tennessee',
           'postal': 'TN',
           'stateface': 'p',
           'type': 'state'},
 'Tennessee': {'ap': 'Tenn.',
               'fips': '47',
               'name': 'Tennessee',
               'postal': 'TN',
               'stateface': 'p',
               'type': 'state'},
 'Texas': {'ap': 'Texas',
           'fips': '48',
           'name': 'Texas',
           'postal': 'TX',
           'stateface': 'q',
           'type': 'state'},
 'UT': {'ap': 'Utah',
        'fips': '49',
        'name': 'Utah',
        'postal': 'UT',
        'stateface': 'r',
        'type': 'state'},
 'Utah': {'ap': 'Utah',
          'fips': '49',
          'name': 'Utah',
          'postal': 'UT',
          'stateface': 'r',
          'type': 'state'},
 'VA': {'ap': 'Va.',
        'fips': '51',
        'name': 'Virginia',
        'postal': 'VA',
        'stateface': 's',
        'type': 'state'},
 'VI': {'ap': '',
        'fips': '78',
        'name': 'Virgin Islands',
        'postal': 'VI',
        'stateface': '',
        'type': ''},
 'VT': {'ap': 'Vt.',
        'fips': '50',
        'name': 'Vermont',
        'postal': 'VT',
        'stateface': 't',
        'type': 'state'},
 'Va.': {'ap': 'Va.',
         'fips': '51',
         'name': 'Virginia',
         'postal': 'VA',
         'stateface': 's',
         'type': 'state'},
 'Vermont': {'ap': 'Vt.',
             'fips': '50',
             'name': 'Vermont',
             'postal': 'VT',
             'stateface': 't',
             'type': 'state'},
 'Virgin Islands': {'ap': '',
                    'fips': '78',
                    'name': 'Virgin Islands',
                    'postal': 'VI',
                    'stateface': '',
                    'type': ''},
 'Virginia': {'ap': 'Va.',
              'fips': '51',
              'name': 'Virginia',
              'postal': 'VA',
              'stateface': 's',
              'type': 'state'},
 'Vt.': {'ap': 'Vt.',
         'fips': '50',
         'name': 'Vermont',
         'postal': 'VT',
         'stateface': 't',
         'type': 'state'},
 'W.Va.': {'ap': 'W.Va.',
           'fips': '54',
           'name': 'West Virginia',
           'postal': 'WV',
           'stateface': 'w',
           'type': 'state'},
 'WA': {'ap': 'Wash.',
        'fips': '53',
        'name': 'Washington',
        'postal': 'WA',
        'stateface': 'u',
        'type': 'state'},
 'WI': {'ap': 'Wis.',
        'fips': '55',
        'name': 'Wisconsin',
        'postal': 'WI',
        'stateface': 'v',
        'type': 'state'},
 'WV': {'ap': 'W.Va.',
        'fips': '54',
        'name': 'West Virginia',
        'postal': 'WV',
        'stateface': 'w',
        'type': 'state'},
 'WY': {'ap': 'Wyo.',
        'fips': '56',
        'name': 'Wyoming',
        'postal': 'WY',
        'stateface': 'x',
        'type': 'state'},
 'Wash.': {'ap': 'Wash.',
           'fips': '53',
           'name': 'Washington',
           'postal': 'WA',
           'stateface': 'u',
           'type': 'state'},
 'Washington': {'ap': 'Wash.',
                'fips': '53',
                'name': 'Washington',
                'postal': 'WA',
                'stateface': 'u',
                'type': 'state'},
 'Washington DC': {'ap': 'D.C.',
                   'fips': '11',
                   'name': 'District of Columbia',
                   'postal': 'DC',
                   'stateface': 'y',
                   'type': ''},
 'Washington, DC': {'ap': 'D.C.',
                    'fips': '11',
                    'name': 'District of Columbia',
                    'postal': 'DC',
                    'stateface': 'y',
                    'type': ''},
 'West Virginia': {'ap': 'W.Va.',
                   'fips': '54',
                   'name': 'West Virginia',
                   'postal': 'WV',
                   'stateface': 'w',
                   'type': 'state'},
 'Wis.': {'ap': 'Wis.',
          'fips': '55',
          'name': 'Wisconsin',
          'postal': 'WI',
          'stateface': 'v',
          'type': 'state'},
 'Wisconsin': {'ap': 'Wis.',
               'fips': '55',
               'name': 'Wisconsin',
               'postal': 'WI',
               'stateface': 'v',
               'type': 'state'},
 'Wyo.': {'ap': 'Wyo.',
          'fips': '56',
          'name': 'Wyoming',
          'postal': 'WY',
          'stateface': 'x',
          'type': 'state'},
 'Wyoming': {'ap': 'Wyo.',
             'fips': '56',
             'name': 'Wyoming',
             'postal': 'WY',
             'stateface': 'x',
             'type': 'state'},
 'ak': {'ap': 'Alaska',
        'fips': '2',
        'name': 'Alaska',
        'postal': 'AK',
        'stateface': 'A',
        'type': 'state'},
 'al': {'ap': 'Ala.',
        'fips': '1',
        'name': 'Alabama',
        'postal': 'AL',
        'stateface': 'B',
        'type': 'state'},
 'ala.': {'ap': 'Ala.',
          'fips': '1',
          'name': 'Alabama',
          'postal': 'AL',
          'stateface': 'B',
          'type': 'state'},
 'alabama': {'ap': 'Ala.',
             'fips': '1',
             'name': 'Alabama',
             'postal': 'AL',
             'stateface': 'B',
             'type': 'state'},
 'alaska': {'ap': 'Alaska',
            'fips': '2',
            'name': 'Alaska',
            'postal': 'AK',
            'stateface': 'A',
            'type': 'state'},
 'american samoa': {'ap': '',
                    'fips': '60',
                    'name': 'American Samoa',
                    'postal': 'AS',
                    'stateface': '',
                    'type': ''},
 'ar': {'ap': 'Ark.',
        'fips': '5',
        'name': 'Arkansas',
        'postal': 'AR',
        'stateface': 'C',
        'type': 'state'},
 'ariz.': {'ap': 'Ariz.',
           'fips': '4',
           'name': 'Arizona',
           'postal': 'AZ',
           'stateface': 'D',
           'type': 'state'},
 'arizona': {'ap': 'Ariz.',
             'fips': '4',
             'name': 'Arizona',
             'postal': 'AZ',
             'stateface': 'D',
             'type': 'state'},
 'ark.': {'ap': 'Ark.',
          'fips': '5',
          'name': 'Arkansas',
          'postal': 'AR',
          'stateface': 'C',
          'type': 'state'},
 'arkansas': {'ap': 'Ark.',
              'fips': '5',
              'name': 'Arkansas',
              'postal': 'AR',
              'stateface': 'C',
              'type': 'state'},
 'as': {'ap': '',
        'fips': '60',
        'name': 'American Samoa',
        'postal': 'AS',
        'stateface': '',
        'type': ''},
 'az': {'ap': 'Ariz.',
        'fips': '4',
        'name': 'Arizona',
        'postal': 'AZ',
        'stateface': 'D',
        'type': 'state'},
 'ca': {'ap': 'Calif.',
        'fips': '6',
        'name': 'California',
        'postal': 'CA',
        'stateface': 'E',
        'type': 'state'},
 'calif.': {'ap': 'Calif.',
            'fips': '6',
            'name': 'California',
            'postal': 'CA',
            'stateface': 'E',
            'type': 'state'},
 'california': {'ap': 'Calif.',
                'fips': '6',
                'name': 'California',
                'postal': 'CA',
                'stateface': 'E',
                'type': 'state'},
 'co': {'ap': 'Colo.',
        'fips': '8',
        'name': 'Colorado',
        'postal': 'CO',
        'stateface': 'F',
        'type': 'state'},
 'colo.': {'ap': 'Colo.',
           'fips': '8',
           'name': 'Colorado',
           'postal': 'CO',
           'stateface': 'F',
           'type': 'state'},
 'colorado': {'ap': 'Colo.',
              'fips': '8',
              'name': 'Colorado',
              'postal': 'CO',
              'stateface': 'F',
              'type': 'state'},
 'conn.': {'ap': 'Conn.',
           'fips': '9',
           'name': 'Connecticut',
           'postal': 'CT',
           'stateface': 'G',
           'type': 'state'},
 'connecticut': {'ap': 'Conn.',
                 'fips': '9',
                 'name': 'Connecticut',
                 'postal': 'CT',
                 'stateface': 'G',
                 'type': 'state'},
 'ct': {'ap': 'Conn.',
        'fips': '9',
        'name': 'Connecticut',
        'postal': 'CT',
        'stateface': 'G',
        'type': 'state'},
 'd.c.': {'ap': 'D.C.',
          'fips': '11',
          'name': 'District of Columbia',
          'postal': 'DC',
          'stateface': 'y',
          'type': ''},
 'dc': {'ap': 'D.C.',
        'fips': '11',
        'name': 'District of Columbia',
        'postal': 'DC',
        'stateface': 'y',
        'type': ''},
 'de': {'ap': 'Del.',
        'fips': '10',
        'name': 'Delaware',
        'postal': 'DE',
        'stateface': 'H',
        'type': 'state'},
 'del.': {'ap': 'Del.',
          'fips': '10',
          'name': 'Delaware',
          'postal': 'DE',
          'stateface': 'H',
          'type': 'state'},
 'delaware': {'ap': 'Del.',
              'fips': '10',
              'name': 'Delaware',
              'postal': 'DE',
              'stateface': 'H',
              'type': 'state'},
 'district of columbia': {'ap': 'D.C.',
                          'fips': '11',
                          'name': 'District of Columbia',
                          'postal': 'DC',
                          'stateface': 'y',
                          'type': ''},
 'federated states of micronesia': {'ap': '',
                                    'fips': '64',
                                    'name': 'Federated States of Micronesia',
                                    'postal': 'FM',
                                    'stateface': '',
                                    'type': ''},
 'fl': {'ap': 'Fla.',
        'fips': '12',
        'name': 'Florida',
        'postal': 'FL',
        'stateface': 'I',
        'type': 'state'},
 'fla.': {'ap': 'Fla.',
          'fips': '12',
          'name': 'Florida',
          'postal': 'FL',
          'stateface': 'I',
          'type': 'state'},
 'florida': {'ap': 'Fla.',
             'fips': '12',
             'name': 'Florida',
             'postal': 'FL',
             'stateface': 'I',
             'type': 'state'},
 'fm': {'ap': '',
        'fips': '64',
        'name': 'Federated States of Micronesia',
        'postal': 'FM',
        'stateface': '',
        'type': ''},
 'ga': {'ap': 'Ga.',
        'fips': '13',
        'name': 'Georgia',
        'postal': 'GA',
        'stateface': 'J',
        'type': 'state'},
 'ga.': {'ap': 'Ga.',
         'fips': '13',
         'name': 'Georgia',
         'postal': 'GA',
         'stateface': 'J',
         'type': 'state'},
 'georgia': {'ap': 'Ga.',
             'fips': '13',
             'name': 'Georgia',
             'postal': 'GA',
             'stateface': 'J',
             'type': 'state'},
 'gu': {'ap': '',
        'fips': '66',
        'name': 'Guam',
        'postal': 'GU',
        'stateface': '',
        'type': ''},
 'guam': {'ap': '',
          'fips': '66',
          'name': 'Guam',
          'postal': 'GU',
          'stateface': '',
          'type': ''},
 'hawaii': {'ap': 'Hawaii',
            'fips': '15',
            'name': 'Hawaii',
            'postal': 'HI',
            'stateface': 'K',
            'type': 'state'},
 'hi': {'ap': 'Hawaii',
        'fips': '15',
        'name': 'Hawaii',
        'postal': 'HI',
        'stateface': 'K',
        'type': 'state'},
 'ia': {'ap': 'Iowa',
        'fips': '19',
        'name': 'Iowa',
        'postal': 'IA',
        'stateface': 'L',
        'type': 'state'},
 'id': {'ap': 'Idaho',
        'fips': '16',
        'name': 'Idaho',
        'postal': 'ID',
        'stateface': 'M',
        'type': 'state'},
 'idaho': {'ap': 'Idaho',
           'fips': '16',
           'name': 'Idaho',
           'postal': 'ID',
           'stateface': 'M',
           'type': 'state'},
 'il': {'ap': 'Ill.',
        'fips': '17',
        'name': 'Illinois',
        'postal': 'IL',
        'stateface': 'N',
        'type': 'state'},
 'ill.': {'ap': 'Ill.',
          'fips': '17',
          'name': 'Illinois',
          'postal': 'IL',
          'stateface': 'N',
          'type': 'state'},
 'illinois': {'ap': 'Ill.',
              'fips': '17',
              'name': 'Illinois',
              'postal': 'IL',
              'stateface': 'N',
              'type': 'state'},
 'in': {'ap': 'Ind.',
        'fips': '18',
        'name': 'Indiana',
        'postal': 'IN',
        'stateface': 'O',
        'type': 'state'},
 'ind.': {'ap': 'Ind.',
          'fips': '18',
          'name': 'Indiana',
          'postal': 'IN',
          'stateface': 'O',
          'type': 'state'},
 'indiana': {'ap': 'Ind.',
             'fips': '18',
             'name': 'Indiana',
             'postal': 'IN',
             'stateface': 'O',
             'type': 'state'},
 'iowa': {'ap': 'Iowa',
          'fips': '19',
          'name': 'Iowa',
          'postal': 'IA',
          'stateface': 'L',
          'type': 'state'},
 'kan.': {'ap': 'Kan.',
          'fips': '20',
          'name': 'Kansas',
          'postal': 'KS',
          'stateface': 'P',
          'type': 'state'},
 'kansas': {'ap': 'Kan.',
            'fips': '20',
            'name': 'Kansas',
            'postal': 'KS',
            'stateface': 'P',
            'type': 'state'},
 'kentucky': {'ap': 'Ky.',
              'fips': '21',
              'name': 'Kentucky',
              'postal': 'KY',
              'stateface': 'Q',
              'type': 'state'},
 'ks': {'ap': 'Kan.',
        'fips': '20',
        'name': 'Kansas',
        'postal': 'KS',
        'stateface': 'P',
        'type': 'state'},
 'ky': {'ap': 'Ky.',
        'fips': '21',
        'name': 'Kentucky',
        'postal': 'KY',
        'stateface': 'Q',
        'type': 'state'},
 'ky.': {'ap': 'Ky.',
         'fips': '21',
         'name': 'Kentucky',
         'postal': 'KY',
         'stateface': 'Q',
         'type': 'state'},
 'la': {'ap': 'La.',
        'fips': '22',
        'name': 'Louisiana',
        'postal': 'LA',
        'stateface': 'R',
        'type': 'state'},
 'la.': {'ap': 'La.',
         'fips': '22',
         'name': 'Louisiana',
         'postal': 'LA',
         'stateface': 'R',
         'type': 'state'},
 'louisiana': {'ap': 'La.',
               'fips': '22',
               'name': 'Louisiana',
               'postal': 'LA',
               'stateface': 'R',
               'type': 'state'},
 'ma': {'ap': 'Mass.',
        'fips': '25',
        'name': 'Massachusetts',
        'postal': 'MA',
        'stateface': 'S',
        'type': 'state'},
 'maine': {'ap': 'Maine',
           'fips': '23',
           'name': 'Maine',
           'postal': 'ME',
           'stateface': 'U',
           'type': 'state'},
 'marshall islands': {'ap': '',
                      'fips': '68',
                      'name': 'Marshall Islands',
                      'postal': 'MH',
                      'stateface': '',
                      'type': ''},
 'maryland': {'ap': 'Md.',
              'fips': '24',
              'name': 'Maryland',
              'postal': 'MD',
              'stateface': 'T',
              'type': 'state'},
 'mass.': {'ap': 'Mass.',
           'fips': '25',
           'name': 'Massachusetts',
           'postal': 'MA',
           'stateface': 'S',
           'type': 'state'},
 'massachusetts': {'ap': 'Mass.',
                   'fips': '25',
                   'name': 'Massachusetts',
                   'postal': 'MA',
                   'stateface': 'S',
                   'type': 'state'},
 'md': {'ap': 'Md.',
        'fips': '24',
        'name': 'Maryland',
        'postal': 'MD',
        'stateface': 'T',
        'type': 'state'},
 'md.': {'ap': 'Md.',
         'fips': '24',
         'name': 'Maryland',
         'postal': 'MD',
         'stateface': 'T',
         'type': 'state'},
 'me': {'ap': 'Maine',
        'fips': '23',
        'name': 'Maine',
        'postal': 'ME',
        'stateface': 'U',
        'type': 'state'},
 'mh': {'ap': '',
        'fips': '68',
        'name': 'Marshall Islands',
        'postal': 'MH',
        'stateface': '',
        'type': ''},
 'mi': {'ap': 'Mich.',
        'fips': '26',
        'name': 'Michigan',
        'postal': 'MI',
        'stateface': 'V',
        'type': 'state'},
 'mich.': {'ap': 'Mich.',
           'fips': '26',
           'name': 'Michigan',
           'postal': 'MI',
           'stateface': 'V',
           'type': 'state'},
 'michigan': {'ap': 'Mich.',
              'fips': '26',
              'name': 'Michigan',
              'postal': 'MI',
              'stateface': 'V',
              'type': 'state'},
 'minn.': {'ap': 'Minn.',
           'fips': '27',
           'name': 'Minnesota',
           'postal': 'MN',
           'stateface': 'W',
           'type': 'state'},
 'minnesota': {'ap': 'Minn.',
               'fips': '27',
               'name': 'Minnesota',
               'postal': 'MN',
               'stateface': 'W',
               'type': 'state'},
 'miss.': {'ap': 'Miss.',
           'fips': '28',
           'name': 'Mississippi',
           'postal': 'MS',
           'stateface': 'Y',
           'type': 'state'},
 'mississippi': {'ap': 'Miss.',
                 'fips': '28',
                 'name': 'Mississippi',
                 'postal': 'MS',
                 'stateface': 'Y',
                 'type': 'state'},
 'missouri': {'ap': 'Mo.',
              'fips': '29',
              'name': 'Missouri',
              'postal': 'MO',
              'stateface': 'X',
              'type': 'state'},
 'mn': {'ap': 'Minn.',
        'fips': '27',
        'name': 'Minnesota',
        'postal': 'MN',
        'stateface': 'W',
        'type': 'state'},
 'mo': {'ap': 'Mo.',
        'fips': '29',
        'name': 'Missouri',
        'postal': 'MO',
        'stateface': 'X',
        'type': 'state'},
 'mo.': {'ap': 'Mo.',
         'fips': '29',
         'name': 'Missouri',
         'postal': 'MO',
         'stateface': 'X',
         'type': 'state'},
 'mont.': {'ap': 'Mont.',
           'fips': '30',
           'name': 'Montana',
           'postal': 'MT',
           'stateface': 'Z',
           'type': 'state'},
 'montana': {'ap': 'Mont.',
             'fips': '30',
             'name': 'Montana',
             'postal': 'MT',
             'stateface': 'Z',
             'type': 'state'},
 'mp': {'ap': '',
        'fips': '69',
        'name': 'Northern Mariana Islands',
        'postal': 'MP',
        'stateface': '',
        'type': ''},
 'ms': {'ap': 'Miss.',
        'fips': '28',
        'name': 'Mississippi',
        'postal': 'MS',
        'stateface': 'Y',
        'type': 'state'},
 'mt': {'ap': 'Mont.',
        'fips': '30',
        'name': 'Montana',
        'postal': 'MT',
        'stateface': 'Z',
        'type': 'state'},
 'n.c.': {'ap': 'N.C.',
          'fips': '37',
          'name': 'North Carolina',
          'postal': 'NC',
          'stateface': 'a',
          'type': 'state'},
 'n.d.': {'ap': 'N.D.',
          'fips': '38',
          'name': 'North Dakota',
          'postal': 'ND',
          'stateface': 'b',
          'type': 'state'},
 'n.h.': {'ap': 'N.H.',
          'fips': '33',
          'name': 'New Hampshire',
          'postal': 'NH',
          'stateface': 'd',
          'type': 'state'},
 'n.j.': {'ap': 'N.J.',
          'fips': '34',
          'name': 'New Jersey',
          'postal': 'NJ',
          'stateface': 'e',
          'type': 'state'},
 'n.m.': {'ap': 'N.M.',
          'fips': '35',
          'name': 'New Mexico',
          'postal': 'NM',
          'stateface': 'f',
          'type': 'state'},
 'n.y.': {'ap': 'N.Y.',
          'fips': '36',
          'name': 'New York',
          'postal': 'NY',
          'stateface': 'h',
          'type': 'state'},
 'nc': {'ap': 'N.C.',
        'fips': '37',
        'name': 'North Carolina',
        'postal': 'NC',
        'stateface': 'a',
        'type': 'state'},
 'nd': {'ap': 'N.D.',
        'fips': '38',
        'name': 'North Dakota',
        'postal': 'ND',
        'stateface': 'b',
        'type': 'state'},
 'ne': {'ap': 'Neb.',
        'fips': '31',
        'name': 'Nebraska',
        'postal': 'NE',
        'stateface': 'c',
        'type': 'state'},
 'neb.': {'ap': 'Neb.',
          'fips': '31',
          'name': 'Nebraska',
          'postal': 'NE',
          'stateface': 'c',
          'type': 'state'},
 'nebraska': {'ap': 'Neb.',
              'fips': '31',
              'name': 'Nebraska',
              'postal': 'NE',
              'stateface': 'c',
              'type': 'state'},
 'nev.': {'ap': 'Nev.',
          'fips': '32',
          'name': 'Nevada',
          'postal': 'NV',
          'stateface': 'g',
          'type': 'state'},
 'nevada': {'ap': 'Nev.',
            'fips': '32',
            'name': 'Nevada',
            'postal': 'NV',
            'stateface': 'g',
            'type': 'state'},
 'new hampshire': {'ap': 'N.H.',
                   'fips': '33',
                   'name': 'New Hampshire',
                   'postal': 'NH',
                   'stateface': 'd',
                   'type': 'state'},
 'new jersey': {'ap': 'N.J.',
                'fips': '34',
                'name': 'New Jersey',
                'postal': 'NJ',
                'stateface': 'e',
                'type': 'state'},
 'new mexico': {'ap': 'N.M.',
                'fips': '35',
                'name': 'New Mexico',
                'postal': 'NM',
                'stateface': 'f',
                'type': 'state'},
 'new york': {'ap': 'N.Y.',
              'fips': '36',
              'name': 'New York',
              'postal': 'NY',
              'stateface': 'h',
              'type': 'state'},
 'nh': {'ap': 'N.H.',
        'fips': '33',
        'name': 'New Hampshire',
        'postal': 'NH',
        'stateface': 'd',
        'type': 'state'},
 'nj': {'ap': 'N.J.',
        'fips': '34',
        'name': 'New Jersey',
        'postal': 'NJ',
        'stateface': 'e',
        'type': 'state'},
 'nm': {'ap': 'N.M.',
        'fips': '35',
        'name': 'New Mexico',
        'postal': 'NM',
        'stateface': 'f',
        'type': 'state'},
 'north carolina': {'ap': 'N.C.',
                    'fips': '37',
                    'name': 'North Carolina',
                    'postal': 'NC',
                    'stateface': 'a',
                    'type': 'state'},
 'north dakota': {'ap': 'N.D.',
                  'fips': '38',
                  'name': 'North Dakota',
                  'postal': 'ND',
                  'stateface': 'b',
                  'type': 'state'},
 'northern mariana islands': {'ap': '',
                              'fips': '69',
                              'name': 'Northern Mariana Islands',
                              'postal': 'MP',
                              'stateface': '',
                              'type': ''},
 'nv': {'ap': 'Nev.',
        'fips': '32',
        'name': 'Nevada',
        'postal': 'NV',
        'stateface': 'g',
        'type': 'state'},
 'ny': {'ap': 'N.Y.',
        'fips': '36',
        'name': 'New York',
        'postal': 'NY',
        'stateface': 'h',
        'type': 'state'},
 'oh': {'ap': 'Ohio',
        'fips': '39',
        'name': 'Ohio',
        'postal': 'OH',
        'stateface': 'i',
        'type': 'state'},
 'ohio': {'ap': 'Ohio',
          'fips': '39',
          'name': 'Ohio',
          'postal': 'OH',
          'stateface': 'i',
          'type': 'state'},
 'ok': {'ap': 'Okla.',
        'fips': '40',
        'name': 'Oklahoma',
        'postal': 'OK',
        'stateface': 'j',
        'type': 'state'},
 'okla.': {'ap': 'Okla.',
           'fips': '40',
           'name': 'Oklahoma',
           'postal': 'OK',
           'stateface': 'j',
           'type': 'state'},
 'oklahoma': {'ap': 'Okla.',
              'fips': '40',
              'name': 'Oklahoma',
              'postal': 'OK',
              'stateface': 'j',
              'type': 'state'},
 'or': {'ap': 'Ore.',
        'fips': '41',
        'name': 'Oregon',
        'postal': 'OR',
        'stateface': 'k',
        'type': 'state'},
 'ore.': {'ap': 'Ore.',
          'fips': '41',
          'name': 'Oregon',
          'postal': 'OR',
          'stateface': 'k',
          'type': 'state'},
 'oregon': {'ap': 'Ore.',
            'fips': '41',
            'name': 'Oregon',
            'postal': 'OR',
            'stateface': 'k',
            'type': 'state'},
 'pa': {'ap': 'Pa.',
        'fips': '42',
        'name': 'Pennsylvania',
        'postal': 'PA',
        'stateface': 'l',
        'type': 'state'},
 'pa.': {'ap': 'Pa.',
         'fips': '42',
         'name': 'Pennsylvania',
         'postal': 'PA',
         'stateface': 'l',
         'type': 'state'},
 'palau': {'ap': '',
           'fips': '70',
           'name': 'Palau',
           'postal': 'PW',
           'stateface': '',
           'type': ''},
 'pennsylvania': {'ap': 'Pa.',
                  'fips': '42',
                  'name': 'Pennsylvania',
                  'postal': 'PA',
                  'stateface': 'l',
                  'type': 'state'},
 'pr': {'ap': '',
        'fips': '72',
        'name': 'Puerto Rico',
        'postal': 'PR',
        'stateface': '',
        'type': ''},
 'puerto rico': {'ap': '',
                 'fips': '72',
                 'name': 'Puerto Rico',
                 'postal': 'PR',
                 'stateface': '',
                 'type': ''},
 'pw': {'ap': '',
        'fips': '70',
        'name': 'Palau',
        'postal': 'PW',
        'stateface': '',
        'type': ''},
 'r.i.': {'ap': 'R.I.',
          'fips': '44',
          'name': 'Rhode Island',
          'postal': 'RI',
          'stateface': 'm',
          'type': 'state'},
 'rhode island': {'ap': 'R.I.',
                  'fips': '44',
                  'name': 'Rhode Island',
                  'postal': 'RI',
                  'stateface': 'm',
                  'type': 'state'},
 'ri': {'ap': 'R.I.',
        'fips': '44',
        'name': 'Rhode Island',
        'postal': 'RI',
        'stateface': 'm',
        'type': 'state'},
 's.c.': {'ap': 'S.C.',
          'fips': '45',
          'name': 'South Carolina',
          'postal': 'SC',
          'stateface': 'n',
          'type': 'state'},
 's.d.': {'ap': 'S.D.',
          'fips': '46',
          'name': 'South Dakota',
          'postal': 'SD',
          'stateface': 'o',
          'type': 'state'},
 'sc': {'ap': 'S.C.',
        'fips': '45',
        'name': 'South Carolina',
        'postal': 'SC',
        'stateface': 'n',
        'type': 'state'},
 'sd': {'ap': 'S.D.',
        'fips': '46',
        'name': 'South Dakota',
        'postal': 'SD',
        'stateface': 'o',
        'type': 'state'},
 'south carolina': {'ap': 'S.C.',
                    'fips': '45',
                    'name': 'South Carolina',
                    'postal': 'SC',
                    'stateface': 'n',
                    'type': 'state'},
 'south dakota': {'ap': 'S.D.',
                  'fips': '46',
                  'name': 'South Dakota',
                  'postal': 'SD',
                  'stateface': 'o',
                  'type': 'state'},
 'tenn.': {'ap': 'Tenn.',
           'fips': '47',
           'name': 'Tennessee',
           'postal': 'TN',
           'stateface': 'p',
           'type': 'state'},
 'tennessee': {'ap': 'Tenn.',
               'fips': '47',
               'name': 'Tennessee',
               'postal': 'TN',
               'stateface': 'p',
               'type': 'state'},
 'texas': {'ap': 'Texas',
           'fips': '48',
           'name': 'Texas',
           'postal': 'TX',
           'stateface': 'q',
           'type': 'state'},
 'tn': {'ap': 'Tenn.',
        'fips': '47',
        'name': 'Tennessee',
        'postal': 'TN',
        'stateface': 'p',
        'type': 'state'},
 'tx': {'ap': 'Texas',
        'fips': '48',
        'name': 'Texas',
        'postal': 'TX',
        'stateface': 'q',
        'type': 'state'},
 'ut': {'ap': 'Utah',
        'fips': '49',
        'name': 'Utah',
        'postal': 'UT',
        'stateface': 'r',
        'type': 'state'},
 'utah': {'ap': 'Utah',
          'fips': '49',
          'name': 'Utah',
          'postal': 'UT',
          'stateface': 'r',
          'type': 'state'},
 'va': {'ap': 'Va.',
        'fips': '51',
        'name': 'Virginia',
        'postal': 'VA',
        'stateface': 's',
        'type': 'state'},
 'va.': {'ap': 'Va.',
         'fips': '51',
         'name': 'Virginia',
         'postal': 'VA',
         'stateface': 's',
         'type': 'state'},
 'vermont': {'ap': 'Vt.',
             'fips': '50',
             'name': 'Vermont',
             'postal': 'VT',
             'stateface': 't',
             'type': 'state'},
 'vi': {'ap': '',
        'fips': '78',
        'name': 'Virgin Islands',
        'postal': 'VI',
        'stateface': '',
        'type': ''},
 'virgin islands': {'ap': '',
                    'fips': '78',
                    'name': 'Virgin Islands',
                    'postal': 'VI',
                    'stateface': '',
                    'type': ''},
 'virginia': {'ap': 'Va.',
              'fips': '51',
              'name': 'Virginia',
              'postal': 'VA',
              'stateface': 's',
              'type': 'state'},
 'vt': {'ap': 'Vt.',
        'fips': '50',
        'name': 'Vermont',
        'postal': 'VT',
        'stateface': 't',
        'type': 'state'},
 'vt.': {'ap': 'Vt.',
         'fips': '50',
         'name': 'Vermont',
         'postal': 'VT',
         'stateface': 't',
         'type': 'state'},
 'w.va.': {'ap': 'W.Va.',
           'fips': '54',
           'name': 'West Virginia',
           'postal': 'WV',
           'stateface': 'w',
           'type': 'state'},
 'wa': {'ap': 'Wash.',
        'fips': '53',
        'name': 'Washington',
        'postal': 'WA',
        'stateface': 'u',
        'type': 'state'},
 'wash.': {'ap': 'Wash.',
           'fips': '53',
           'name': 'Washington',
           'postal': 'WA',
           'stateface': 'u',
           'type': 'state'},
 'washington': {'ap': 'Wash.',
                'fips': '53',
                'name': 'Washington',
                'postal': 'WA',
                'stateface': 'u',
                'type': 'state'},
 'washington dc': {'ap': 'D.C.',
                   'fips': '11',
                   'name': 'District of Columbia',
                   'postal': 'DC',
                   'stateface': 'y',
                   'type': ''},
 'washington, dc': {'ap': 'D.C.',
                    'fips': '11',
                    'name': 'District of Columbia',
                    'postal': 'DC',
                    'stateface': 'y',
                    'type': ''},
 'west virginia': {'ap': 'W.Va.',
                   'fips': '54',
                   'name': 'West Virginia',
                   'postal': 'WV',
                   'stateface': 'w',
                   'type': 'state'},
 'wi': {'ap': 'Wis.',
        'fips': '55',
        'name': 'Wisconsin',
        'postal': 'WI',
        'stateface': 'v',
        'type': 'state'},
 'wis.': {'ap': 'Wis.',
          'fips': '55',
          'name': 'Wisconsin',
          'postal': 'WI',
          'stateface': 'v',
          'type': 'state'},
 'wisconsin': {'ap': 'Wis.',
               'fips': '55',
               'name': 'Wisconsin',
               'postal': 'WI',
               'stateface': 'v',
               'type': 'state'},
 'wv': {'ap': 'W.Va.',
        'fips': '54',
        'name': 'West Virginia',
        'postal': 'WV',
        'stateface': 'w',
        'type': 'state'},
 'wy': {'ap': 'Wyo.',
        'fips': '56',
        'name': 'Wyoming',
        'postal': 'WY',
        'stateface': 'x',
        'type': 'state'},
 'wyo.': {'ap': 'Wyo.',
          'fips': '56',
          'name': 'Wyoming',
          'postal': 'WY',
          'stateface': 'x',
          'type': 'state'},
 'wyoming': {'ap': 'Wyo.',
             'fips': '56',
             'name': 'Wyoming',
             'postal': 'WY',
             'stateface': 'x',
             'type': 'state'}}
